tinyMCE.addI18n('en.imgmanager_ext_dlg',{
missing_alt: "Are you sure you want to continue without including Alternate Text for the image? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
delta_width: 0,
delta_height: 0,
'0':'Original',
'-90': '90&deg; CW',
'90': '90&deg; CCW',
'180': '180&deg;',
'vertical': 'Flip Vertical',
'horizontal': 'Flip Horizontal',
'view_images': 'Thumbnail View',
'view_list': 'List View',
'use_thumbnail': 'Use associated thumbnail for popup link?',
'resize': 'Resize',
'rotate': 'Rotate',
'proportional': 'Proportional',
'cropped': 'Cropped',
'mode': 'Mode',
'quality': 'Quality',
'size': 'Size',
'thumbnail': 'Thumbnail',
'transform': 'Transform',
'width': 'Width',
'height': 'Height',
'create_thumbnail': 'Create Thumbnail',
'delete_thumbnail': 'Delete Thumbnail?',
'message_images': 'Click on an image to view its properties, double-click to insert it. CTRL+Click selects multiple images.',
'message_list': 'Click on an image name to insert, click to the right of the name to view its properties. CTRL+Click selects multiple images.',
'no_src': 'Please select an image or enter an image URL.',
'no_popup_src' : 'Please enter a url for the popup image',
'upload_resize_tip' : 'Resize::Resize the uploaded images to fit within the specified width and height whilst maintaining the aspect ratio of the original image.',
'upload_thumbnail_tip' : 'Thumbnail::Create a thumbnail of the uploaded image using the specified dimensions whilst maintaining the aspect ratio of the original image. If Crop to Fit is checked the thumbnail will be cropped to fit within the dimensions.',
'upload_thumbnail_crop' : 'Crop To Fit',
'upload_thumbnail_crop_tip' : 'Crop To Fit::Crop the thumbnail to fit within the specified dimensions',
'greyscale' : 'Greyscale',
'sepia'	: ' Sepia',
'invert' : 'Negative',
'lighten' : 'Lighten',
'darken' : 'Darken',
'saturate' : 'Boost',
'desaturate' : 'Fade',
'threshold' : 'B&W',
'halftone' : 'Comic Book'
});